### PR TITLE
Add about and FAQ page

### PR DESCRIPTION
**Pull request by narrator0**
Add the about page and FAQ page to to be served by JupyterHub as static pages.

## Files Created

* `/pages/about.html`
* `/pages/faq.html`
* `/pages/example.page.html`
* `/css/about.css`
* `/css/custom.css`

> `/pages/example.page.html` is a starter template for future pages that have all the html from JupyterHub.

### CODE REVIEW

**Comment by narrator0** [comment]
Basically finished. Still waiting for:

- [x] description on the about page
- [x] Kelvin's image

**Comment by celine168** [comment]
Out of curiosity, did you try the new pages out on the staging JupyterHub?

**Comment by narrator0** [comment]
This is the problem without a staging branch. I have to merge them first before I can test on staging.

**Comment by moorepants** [comment]
Can't you setup staging to pull from this PR? If you want to have the staging hub display the changes in a given PR before that PR is merged to master, then why not just have staging pull from this PR to show us that things are working?

**Comment by narrator0** [comment]
I can setup that with a staging branch. We can discuss that in the next meeting.

**Pull request merged**
